"""empty message

Revision ID: 292addf1bded
Revises: 8ae375347211
Create Date: 2021-03-12 10:53:15.208885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292addf1bded'
down_revision = '8ae375347211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('photo', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
