"""empty message

Revision ID: 845bd3f6dd60
Revises: 2cebc5feb870
Create Date: 2021-03-12 10:21:44.838996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845bd3f6dd60'
down_revision = '2cebc5feb870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('photo_filename', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'photo_filename')
    # ### end Alembic commands ###
